### ISSUE TITLE
Tuya Socket not responding to Home App

### ISSUE THREAD

**Issue by j3nk216** [codetheweb/homebridge-tuya#8]
Hey guys,

thanks for the amazing tuya homebridge plugin.

So far, I was able to install homebridge and the tuya plugin on my raspberry pi 3 model b+ and figure out the ID, key and IP address of my tuya socket. 

Moreover the home App on my iPhone is recognizing the device and shows me the controls for it. It seems to have a stabil connection to the raspberry, because the home app shows me an active connection as long as the homebridge application is running on the raspberry pi and it turns to "no response" as soon as I terminate homebridge on the raspberry. In the terminal window I can see HomeBridge found the right IP Adress of the device although I have not included it in the config.json file. 

However, the home app is not reflecting reality, because I can switch the socket on and off using the app, but the tuya device is not reacting. Vice versa, if I turn the tuya socket on and off manually (using the button on it), the home app doesn't show any status changes. The device reacts fine to the smart life app and the google home voice assistant. 

Sadly I ran out of option, so I thought you guys might be able to help me. 

Thanks for your help!

**Comment by j3nk216** [comment]
To give you some more input, this is the output of the DEBUG=* homebridge command, if I turn on the light in my home app (Device ID and "t" anonymized):

`EventedHTTPServer [::ffff:192.168.0.7] HTTP request: /characteristics +12s
  HAPServer [CC:22:3D:E3:CE:32] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":18,"value":1}] +2ms
  Accessory [Homebridge] Setting Characteristic "On" to value 1 +1ms
  TuyAPI Payload: +12s
  TuyAPI { devId: 'xxxxxxxxxxxxxxxxxxx',
  TuyAPI   uid: '',
  TuyAPI   t: 'xxxxxxxxxxx',
  TuyAPI   dps: { '1': true } } +1ms
  TuyAPI Socket attempt 1 +6ms
  TuyAPI Sending this data:  000055aa000000000000000700000087332e31666431376265303230373533663130394a455858507458415038336446616849495737796a304a45464c574f4b56413359646961794973624e7368782b6f37676b2b386a2f674f496c59366b6d2b503258456c585a5677457a787633305a6c316253376177616274506e56704a573254413949572f622b504e42453d000000000000aa55 +1ms
  TuyAPI Socket connected. +5ms
  TuyAPI Received data back: +2s
  TuyAPI 000055aa00000000000000080000009f00000000332e316166613734626532663266393564653071653862307a515a4348716551557271586a6c656561745143646e61553457433732582f755977516d32616e4b4931386973324e473879796343486364426d6579476a4b484a676d7a59432b6c32312f36527954306b4358584775554e3638336438795954716c6a676a6e682b7a645364386e69396538655754726233515571589f1d840000aa55 +1ms
  EventedHTTPServer [::ffff:192.168.0.7] Muting event '3.18' notification for this connection since it originated here. +2s
  EventedHTTPServer [::ffff:192.168.0.7] HTTP Response is finished +2ms`

**Comment by codetheweb** [comment]
Can you please try switching your device on and off while Homebridge is running in debug mode, and post the resulting log?  You can run Homebridge in debug mode with `DEBUG=* homebridge`.

**Comment by soorb** [comment]
I have the exact same issue. I have wifi switches that I installed with tuya smart.app. Got the "id" and "key" and added to Homebrige and HomeKit. Everything works fine, but when I want to turn my switches on manually the state in HomeKit won´t update? In Tuya smart I can see it updates in milliseconds. So I know it sends the package back? If I close HomeKit and open it, the update happens?

When in debug mode I can see changes when I switch in HomeKit but not manually.




 TuyAPI Payload:  { gwId: 'xxx', devId: 'xxx' } +0ms
  TuyAPI Send attempt 1 +6ms
  TuyAPI Sending this data: 000055aa000000000000000a000000467b2267774964223a223330353030363130383430643865383161366236222c226465764964223a223330353030363130383430643865383161366236227d000000000000aa55 +1ms
  TuyAPI Connect 192.168.1.118 +1ms
  Accessory [Homebridge] Getting value for Characteristic "On" +10ms
[2019-2-18 23:46:24] [Broadlink RM] Fönsterlampan i Vardagsrummet getSwitchState: true
  Accessory [Homebridge] Got Characteristic "On" value: true +0ms
  Accessory [Homebridge] Getting value for Characteristic "On" +0ms
[2019-2-18 23:46:24] [Broadlink RM] Taklampan i Vardagsrummet getSwitchState: false
  Accessory [Homebridge] Got Characteristic "On" value: false +1ms
  TuyAPI Socket connected. +5ms
  TuyAPI Received data back: 192.168.1.118 +5ms
  TuyAPI 00005xxx33035303036313038343064386538xxxa747275652c2232223a307d7da6272de70000aa55 +0ms
  TuyAPI Data: 192.168.1.118 { devId: 'xxx', dps: { '1': true, '2': 0 } } 10 +1ms
  TuyAPI Disconnect +1ms
  Accessory [Homebridge] Got Characteristic "On" value: true +10ms
  EventedHTTPServer [::ffff:192.168.1.101] Muting event '53.10' notification for this connection since it originated here. +1ms
  EventedHTTPServer [::ffff:192.168.1.116] Sending HTTP event '53.10' with data: {"characteristics":[{"aid":53,"iid":10,"value":true}]} +1ms
  EventedHTTPServer [::ffff:192.168.1.101] HTTP Response is finished +1ms
  TuyAPI Socket closed: 192.168.1.118 +3ms
  EventedHTTPServer [::ffff:192.168.1.116] HTTP request: /characteristics +103ms
  HAPServer [xxx] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":10,"iid":10,"value":1}] +0ms
  Accessory [Homebridge] Setting Characteristic "On" to value 1 +1ms
[2019-2-18 23:46:24] [Broadlink RM] Taklampan i Vardagsrummet setSwitchState: true
[2019-2-18 23:46:24] [Broadlink RM] Taklampan i Vardagsrummet sendHex (192.168.1.43; xxx) b2002403085a080a082c082c080a082c080a092b080a0909092b0909092b092b080a0909092c080a082c082b090a082c080a082c080a080a082c080a082c082c080a080a082c0909082c0909082c082c0909092b080a092b080a0909092b092b080a092b080a092b0909080a092b0909092b092b080a082c080a092b080a0909082c080a092b08000156085a080a082c082c080a082c080a082c080a080a082c080a082c082btjyja092b082c080a082c080a082c080a080a082c080a082c082b080a090a082b0909092b092b080a092b080a082c080a080a082c080a082c082c080a080a082c080a082c080a082c082b090a082b090a082b080b070a092b092b080a092b080a092b080a080a082c080a082c082c080a082c080a082c080a080a082c080a082b09000155085a080a082c092b080a082c080a082c080a080a08gggg80a082c082b090a082b0909092b090a0809082c080a082c080001550959080a082c082c0hhlkhkj90a082c080a080a082c080a082c082c080a082c080a082c080a080a082c080a082b080005dc00000000
  EventedHTTPServer [::ffff:192.168.1.101] Sending HTTP event '10.10' with data: {"characteristics":[{"aid":10,"iid":10,"value":true}]} +6ms
  EventedHTTPServer [::ffff:192.168.1.116] Muting event '10.10' notification for this connection since it originated here. +0ms
  EventedHTTPServer [::ffff:192.168.1.116] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.101] HTTP request: /characteristics +20s
  HAPServer [xxx] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":53,"iid":10,"value":0}] +1ms
  Accessory [Homebridge] Setting Characteristic "On" to value 0 +0ms
  TuyAPI Payload: 192.168.1.118 +20s
  TuyAPI { devId: 'xxx',
  TuyAPI   gwId: 'xxx',
  TuyAPI   uid: '',
  TuyAPI   t: '1550530004',
  TuyAPI   dps: { '1': false } } +0ms
  TuyAPI Send attempt 1 +6ms
  TuyAPI Sending this data: 000055aa00000xxx31623939343737633338323362643832375875694e346a773444362f696e3456696463776c332b2f657348727856387641735351667776345335636450504b4a43772f4f706d416830393xxxxx533143344f68663539594b49456e6e51655456464e50534e78595378353050534d4d4d376d7744413d3d000000000000aa55 +2ms
  TuyAPI Connect 192.168.1.118 +0ms
  TuyAPI Socket connected. +4ms
  TuyAPI Received data back: 192.168.1.118 +12ms
  TuyAPI 000055aa00000000000000070000000c00000000789370910000aa55 +1ms
  TuyAPI undefined 192.168.1.118 undefined 7 +0ms
  TuyAPI Disconnect +0ms
  EventedHTTPServer [::ffff:192.168.1.101] Muting event '53.10' notification for this connection since it originated here. +27ms
  EventedHTTPServer [::ffff:192.168.1.116] Sending HTTP event '53.10' with data: {"characteristics":[{"aid":53,"iid":10,"value":false}]} +0ms
  EventedHTTPServer [::ffff:192.168.1.101] HTTP Response is finished +0ms
  TuyAPI Socket closed: 192.168.1.118 +2ms
  EventedHTTPServer [::ffff:192.168.1.116] HTTP request: /characteristics +40ms
  HAPServer [xxx] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":10,"iid":10,"value":0}] +5ms
  Accessory [Homebridge] Setting Characteristic "On" to value 0 +0ms
[2019-2-18 23:46:44] [Broadlink RM] Taklampan i Vardagsrummet setSwitchState: false
[2019-2-18 23:46:44] [Broadlink RM] Taklampan i Vardagsrummet sendHex (192.168.1.43; xxx) b2002403075b080a082c082c080a082c070b082c080b070a082d070b072d072c080b070b072d070b072d072d070b082c070b072c080b070a082d070b072c082c080a080a082c080b072d070a082c082c080a082c080a082c080a080a082c082c070b072d070b082c080a080a072d080a072d070b082c082c070b072d070kjjkj82c080a082c080a080a082c080a072d082c080a080a082c080a082c082c070b082c070b082c080a080a0yu0b072d072c080b072c080a082c080a080a082c080a082c082c080a080a082c080a082c082c070b082c070b082c070b070a082d070b072d082b080a080a082d080a072d070b072d072c080a082c080a082c080a080a082c082c080a082c070b082c080a080a082c080a082c070b082c082c070b082b080b080a072d070b082b08000157075b070b082c082b080b082b080b072c080b070b072d070a082d072c080b070a082d070a082c082d070b072c080b072c080a080a082c080a082d072c080a080a082c080a082c080a082c082c080a082c070b082c070b070b082c072d070b072d080a082c080a080a082c080a082c070b082c082c070b082c070b070b072d080a072c08000156085a080a082c082c080a082c080a082c080a080a082c080a072d082c070b080a082c080a082c082c080a082c080a082c080a080a082c080a072d082c070b070b082c080a072d070b072d082c070b072d070b072d070b070b082c082b080b082b080b072d070b070b072c080b072c080a082d072c080a082c080a080a082c070b082c070005dc00000000
  EventedHTTPServer [::ffff:192.168.1.101] Sending HTTP event '10.10' with data: {"characteristics":[{"aid":10,"iid":10,"value":false}]} +5ms
  EventedHTTPServer [::ffff:192.168.1.116] Muting event '10.10' notification for this connection since it originated here. +1ms
  EventedHTTPServer [::ffff:192.168.1.116] HTTP Response is finished +0ms

**Comment by codetheweb** [comment]
If you physically change a switch, it doesn't update automatically in the app because the plugin doesn't utilize TuyAPI's event-based programming at the moment.  This is a known bug, and will hopefully be addressed soon.
